name: '@intersect-engine/action-forum-poster'
description: 'Action to publish Intersect Engine releases to the AscensionGameDev community forum'
author: 'Ascension Game Dev'
inputs:
  api-key:
    required: true
    description: 'IPB API Key'
  build:
    required: true
    description: 'Build run number'
  hash:
    required: true
    description: 'Commit hash'
  version:
    required: true
    description: 'The version identifier'
runs:
  using: 'node16'
  main: 'dist/index.js'
